### ISSUE TITLE
Add Resources Directory for Default Assets

### ISSUE THREAD

**Issue by MitchellOpitz** [MitchellOpitz/Automatic-Rule-Tile-Generator#5]
This issue proposes adding a new directory named "Resources" to the project. This directory will house default assets for users to get started quickly.

- [x] The directory will contain a default rule tile template file.
- [x] It will also include a basic tilemap sample file for reference.
- [x] Additionally, consider including an optional detailed tilemap sample for more complex use cases.

**Comment by MitchellOpitz** [comment]
I've completed the first two tasks: adding a default rule tile template file and a basic tilemap template file (commit: 4854eec). Including an optional detailed tilemap sample is still pending. I'm keeping this issue open as a reminder to finish it, but moving on to the next issue for now.

**Comment by MitchellOpitz** [comment]
### Update Progress:

I have reviewed and updated the existing usage instructions in the README file to ensure clarity and accuracy for new users. The instructions now reflect the current functionalities of the Auto Rule Tile Generator tool.

### Next Steps:

I am in the process of creating a tilemap sample with 3 variant tilemaps, which will be used to update the screenshots in the README. Currently, I only have the tilemap template.

### Completion Plan:

After creating the tilemap samples and variants, I will capture screenshots to accompany the updated instructions in the README.

**Comment by BrainfartStudio** [comment]
This update addresses the successful implementation of default rule tile and tilemap functionality.

- The code now sets the default rule tile and tilemap to the assets located in the "Resources" directory.
- Importantly, the issue of values resetting on object click has been resolved, ensuring persistence.

### Screenshots in README - On Hold (Separate Issue)

Screenshots for the README were initially planned (see issue #7). I will be creating a YouTube video demonstrating the Auto Rule Tile Generator tool's functionalities, which will likely supersede the need for additional screenshots in the README.
